x-app: &base-app
  build:
    context: .
    target: core
  environment: &base-app-env
    POSTGRES_PASSWORD: dev
    POSTGRES_USER: dev
    POSTGRES_DB: dev
    POSTGRES_PORT: 5432
    POSTGRES_HOST: db
  volumes:
    - ./requirements:/app/requirements
    - ./core:/app/core
    - ./${SERVICE_NAME}:/app/${SERVICE_NAME}
  ports:
    - 8000:8000
  depends_on:
    db:
      condition: service_healthy

volumes:
  cache:

services:
  db:
    image: timescale/timescaledb-ha:pg15
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    ports:
      - "5435:5432"
    healthcheck:
      test: pg_isready -U dev -d dev
      interval: 10s
      timeout: 5s
      retries: 5

  dev:
    <<: *base-app
    build:
      context: .
      target: dev-${SERVICE_NAME}
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: '${SERVICE_NAME}.settings.local'
      API_AUTH_TOKENS: insecure1,insecure2,insecure3
      MIJN_AMS_AUTH_TOKENS: mijn-ams-1,mijn-ams-2
      SECRET_KEY: secret-key-for-development
      EDITOR_GROUP_ID: editor-group-id-for-development
      PUBLISHER_GROUP_ID: publisher-group-id-for-development

  test:
    <<: *base-app
    build:
      context: .
      target: dev-${SERVICE_NAME}
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-aapp/images}/dev-${SERVICE_NAME}:${VERSION:-latest}
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: '${SERVICE_NAME}.settings.base'
      API_AUTH_TOKENS: insecure1,insecure2,insecure3
      MIJN_AMS_AUTH_TOKENS: mijn-ams-1,mijn-ams-2
      SECRET_KEY: secret-key-for-testing
      EDITOR_GROUP_ID: editor-group-id-for-testing
      PUBLISHER_GROUP_ID: publisher-group-id-for-testing
    command: pytest

  app:
    <<: *base-app
    build:
      context: .
      target: app-${SERVICE_NAME}
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-aapp/images}/app-${SERVICE_NAME}:${VERSION:-latest}
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: '${SERVICE_NAME}.settings.otap'
    command: /app/deploy/docker-run.sh

  openapi-diff:
    image: openapitools/openapi-diff:latest
    volumes:
      - ./${SERVICE_NAME}:/specs:ro