x-app: &base-app
  build:
    context: .
    target: core
  environment: &base-app-env
    POSTGRES_PASSWORD: dev
    POSTGRES_USER: dev
    POSTGRES_DB: dev
    POSTGRES_PORT: 5432
    POSTGRES_HOST: db
    API_AUTH_TOKENS: insecure1,insecure2,insecure3
    MIJN_AMS_AUTH_TOKENS: mijn-ams-1,mijn-ams-2
  env_file:
    - .env
  volumes:
    - ./requirements:/app/requirements
    - ./core:/app/core
    - ./${SERVICE_NAME}:/app/${SERVICE_NAME}
  ports:
    - 8000:8000
  depends_on:
    db:
      condition: service_healthy

volumes:
  db_data:
  cache:

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      PGDATA: /data
    volumes:
      - db_data:/data
    ports:
      - "5435:5432"
    healthcheck:
      test: pg_isready -U dev -d dev
      interval: 10s
      timeout: 5s
      retries: 5

  dev:
    <<: *base-app
    build:
      context: .
      target: dev-${SERVICE_NAME}
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: '${SERVICE_NAME}.settings.local'

  test:
    <<: *base-app
    build:
      context: .
      target: dev-${SERVICE_NAME}
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-aapp/images}${SERVICE_NAME}:${VERSION:-latest}
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: '${SERVICE_NAME}.settings.local'
    command: pytest

  app:
    <<: *base-app
    build:
      context: .
      target: app-${SERVICE_NAME}
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-aapp/images}/${SERVICE_NAME}:${VERSION:-latest}
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: '${SERVICE_NAME}.settings.otap'
    command: /app/deploy/docker-run.sh
