x-app: &base-app
  build:
    context: .
    target: core
  environment: &base-app-env
    POSTGRES_PASSWORD: dev
    POSTGRES_USER: dev
    POSTGRES_DB: dev
    POSTGRES_PORT: 5432
    POSTGRES_HOST: db
    API_AUTH_TOKENS: insecure1,insecure2,insecure3
    MIJN_AMS_AUTH_TOKENS: mijn-ams-1,mijn-ams-2
  ports:
    - 8000:8000
  depends_on:
    db:
      condition: service_healthy

volumes:
  db_data:
  cache:

services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
      PGDATA: /data
    volumes:
      - db_data:/data
    ports:
      - "5435:5432"
    healthcheck:
      test: pg_isready -U dev -d dev
      interval: 10s
      timeout: 5s
      retries: 5

  dev-city-pass:
    <<: *base-app
    build:
      context: .
      target: dev-city-pass
    volumes:
      - ./requirements:/app/requirements
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: "city_pass.settings.local"

  test-city-pass:
    <<: *base-app
    build:
      context: .
      target: dev-city-pass
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-aapp/images/city-pass}:${VERSION:-latest}
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: "city_pass.settings.local"
    command: pytest

  app-city-pass:
    <<: *base-app
    build:
      context: .
      target: app-city-pass
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-aapp/images/city-pass}:${VERSION:-latest}
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: "city_pass.settings.otap"
    command: /app/deploy/docker-run.sh
