x-app: &base-app
  build:
    context: .
    target: core
  environment: &base-app-env
    POSTGRES_PASSWORD: dev
    POSTGRES_USER: dev
    POSTGRES_DB: dev
    POSTGRES_PORT: 5432
    POSTGRES_HOST: db
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_PASSWORD: password
  volumes:
    - ./requirements:/app/requirements
    - ./core:/app/core
    - ./${SERVICE_NAME}:/app/${SERVICE_NAME}
  ports:
    - 8000:8000
  depends_on:
    redis:
      condition: service_healthy
    db:
      condition: service_healthy
volumes:
  cache:

services:
  db:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - ./deploy/init_pgtrgm.sql:/docker-entrypoint-initdb.d/init_pgtrgm.sql
    ports:
      - "5435:5432"
    healthcheck:
      test: pg_isready -U dev -d dev
      interval: 10s
      timeout: 5s
      retries: 5

  dev:
    <<: *base-app
    build:
      context: .
      target: dev-${SERVICE_NAME}
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: '${SERVICE_NAME}.settings.local'
      API_AUTH_TOKENS: insecure1,insecure2,insecure3
      MIJN_AMS_AUTH_TOKENS: mijn-ams-1,mijn-ams-2
      SECRET_KEY: secret-key-for-development
      EDITOR_GROUP_ID: editor-group-id-for-development
      PUBLISHER_GROUP_ID: publisher-group-id-for-development

  test:
    <<: *base-app
    build:
      context: .
      target: dev-${SERVICE_NAME}
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-aapp/images}/dev-${SERVICE_NAME}:${VERSION:-latest}
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: '${SERVICE_NAME}.settings.base'
      API_AUTH_TOKENS: insecure1,insecure2,insecure3
      MIJN_AMS_AUTH_TOKENS: mijn-ams-1,mijn-ams-2
      SECRET_KEY: secret-key-for-testing
      EDITOR_GROUP_ID: editor-group-id-for-testing
      PUBLISHER_GROUP_ID: publisher-group-id-for-testing
    command: pytest

  app:
    <<: *base-app
    build:
      context: .
      target: app-${SERVICE_NAME}
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-aapp/images}/app-${SERVICE_NAME}:${VERSION:-latest}
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: '${SERVICE_NAME}.settings.otap'
    command: /app/deploy/docker-run.sh

  lint:
    <<: *base-app
    build:
      context: .
      target: dev-${SERVICE_NAME}
    volumes:
    - ./bridge:/app/bridge
    - ./city_pass:/app/city_pass
    - ./construction_work:/app/construction_work
    - ./contact:/app/contact
    - ./image:/app/image
    - ./modules:/app/modules
    - ./notification:/app/notification
    - ./waste:/app/waste

  openapi-diff:
    image: openapitools/openapi-diff:latest
    volumes:
      - ./${SERVICE_NAME}:/specs:ro

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    command: redis-server --requirepass password --maxmemory 100mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      timeout: 3s