x-app: &base-app
  build:
    context: .
    target: app-${SERVICE_NAME}
  environment: &base-app-env
    POSTGRES_PASSWORD: dev
    POSTGRES_USER: dev
    POSTGRES_DB: dev
    POSTGRES_PORT: 5432
    POSTGRES_HOST: db
    REDIS_HOST: redis
    REDIS_PORT: 6379
    REDIS_PASSWORD: password
    ALLOW_NOTIFICATION_DB_MIGRATE: "true"
  volumes:
    - ./core:/app/core
    - ./${SERVICE_NAME}:/app/${SERVICE_NAME}
    - ./pyproject.toml:/app/pyproject.toml
    - ./manage.py:/app/manage.py
  ports:
    - 8000:8000
  depends_on:
    redis:
      condition: service_healthy
    db:
      condition: service_healthy
volumes:
  cache:

services:
  db:
    image: timescale/timescaledb:latest-pg15
    environment:
      POSTGRES_DB: dev
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: dev
    volumes:
      - ./deploy/init_pgtrgm.sql:/docker-entrypoint-initdb.d/init_pgtrgm.sql
      - ./deploy/init_notification_database.sql:/docker-entrypoint-initdb.d/init_notification_database.sql
    ports:
      - "5435:5432"
    healthcheck:
      test: pg_isready -U dev -d dev
      interval: 10s
      timeout: 5s
      retries: 5

  dev:
    <<: *base-app
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-aapp/images}/dev-${SERVICE_NAME}:${VERSION:-latest}
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: "${SERVICE_NAME}.settings.local"
      API_AUTH_TOKENS: insecure1,insecure2,insecure3
      MIJN_AMS_AUTH_TOKENS: mijn-ams-1,mijn-ams-2
      SECRET_KEY: secret-key-for-development
      EDITOR_GROUP_ID: editor-group-id-for-development
      PUBLISHER_GROUP_ID: publisher-group-id-for-development
    command: uv run python ./manage.py runserver 0.0.0.0:8000

  test:
    <<: *base-app
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-aapp/images}/test-${SERVICE_NAME}:${VERSION:-latest}
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: "${SERVICE_NAME}.settings.base"
      API_AUTH_TOKENS: insecure1,insecure2,insecure3
      MIJN_AMS_AUTH_TOKENS: mijn-ams-1,mijn-ams-2
      SECRET_KEY: secret-key-for-testing
      EDITOR_GROUP_ID: editor-group-id-for-testing
      PUBLISHER_GROUP_ID: publisher-group-id-for-testing
    command: uv run pytest

  app:
    <<: *base-app
    image: ${REGISTRY:-localhost:5000}/${REPOSITORY:-aapp/images}/app-${SERVICE_NAME}:${VERSION:-latest}
    environment:
      <<: *base-app-env
      DJANGO_SETTINGS_MODULE: "${SERVICE_NAME}.settings.otap"
    command: /app/deploy/docker-run-async.sh

  lint:
    <<: *base-app
    volumes:
      - ./core:/app/core
      - ./manage.py:/app/manage.py
      - ./bridge:/app/bridge
      - ./city_pass:/app/city_pass
      - ./construction_work:/app/construction_work
      - ./contact:/app/contact
      - ./image:/app/image
      - ./modules:/app/modules
      - ./notification:/app/notification
      - ./waste:/app/waste
      - ./survey:/app/survey
      - ./pyproject.toml:/app/pyproject.toml
      - ./requirements.txt:/app/requirements.txt
      - ./uv.lock:/app/uv.lock
  openapi-diff:
    image: openapitools/openapi-diff:latest
    volumes:
      - ./${SERVICE_NAME}:/specs:ro

  redis:
    image: redis:6.2
    ports:
      - "6379:6379"
    command: redis-server --requirepass password --maxmemory 100mb --maxmemory-policy allkeys-lru
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      retries: 5
      timeout: 3s

  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_BOOTSTRAP_ADMIN_USERNAME: admin
      KC_BOOTSTRAP_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    command: ["start-dev"]
